name: Solution - DataOps Pipeline
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      keyvault_name:
        required: true
        type: string
      secret_client_id_name:
        required: true
        type: string
      secret_client_secret_name:
        required: true
        type: string
jobs:
  # 1. Dispara a validação de Python (Linting, Type Check, Pytest)
  Python-CI:
    uses: gonntt/DevSecOps---workflow-jobs/.github/workflows/ci-dataops-python.yml@main
    secrets: inherit

  # 2. Dispara a validação de SQL (SQLFluff) em paralelo
  SQL-CI:
    uses: gonntt/DevSecOps---workflow-jobs/.github/workflows/ci-dataops-sql.yml@main
    secrets: inherit

  # 3. Dispara o Deploy via Databricks Asset Bundles
  Deploy-Databricks-PRD:
    # Garante que o deploy aguarda o sucesso do CI de Python e SQL
    needs: [Python-CI, SQL-CI]
    # Garante que só há deploy em merges/pushes na main, nunca em Pull Requests
    if: github.ref == 'refs/heads/main'
    uses: gonntt/DevSecOps---workflow-jobs/.github/workflows/databricks-deploy.yml@main
    with:
      environment: ${{ inputs.environment }}
      keyvault_name: ${{ inputs.keyvault_name }}
      secret_client_id_name: ${{ inputs.secret_client_id_name }}
      secret_client_secret_name: ${{ inputs.secret_client_secret_name }}
    secrets: inherit 